adapters: 
  - http
  - ws
debug: false
enableVerify: true
verifyKey: 191932207
singleMode: false
cacheSize: 4096
adapterSettings: 
  http:
    host: localhost
    port: 8080
    cors: [*]
  ws:
    host: localhost
    port: 8080
    reservedSyncId: -1
